# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hf-hub-utils',
                'doc_host': 'https://deep-diver.github.io',
                'git_url': 'https://github.com/deep-diver/hf-hub-utils',
                'lib_path': 'hf_hub_utils'},
  'syms': {'hf_hub_utils.core': {'hf_hub_utils.core.foo': ('core.html#foo', 'hf_hub_utils/core.py')}}}
